// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFileToInputDir(arg1, arg2) {
  return window['go']['desktop']['Shell']['CopyFileToInputDir'](arg1, arg2);
}

export function DeleteSession(arg1, arg2) {
  return window['go']['desktop']['Shell']['DeleteSession'](arg1, arg2);
}

export function DeleteSetting(arg1, arg2, arg3) {
  return window['go']['desktop']['Shell']['DeleteSetting'](arg1, arg2, arg3);
}

export function EnsureAgentRunning(arg1) {
  return window['go']['desktop']['Shell']['EnsureAgentRunning'](arg1);
}

export function GetSettings() {
  return window['go']['desktop']['Shell']['GetSettings']();
}

export function GetSettingsSchema() {
  return window['go']['desktop']['Shell']['GetSettingsSchema']();
}

export function GetSessionEvent(arg1, arg2, arg3) {
  return window['go']['desktop']['Shell']['GetSessionEvent'](arg1, arg2, arg3);
}

export function HasMissingRequired() {
  return window['go']['desktop']['Shell']['HasMissingRequired']();
}

export function InspectSession(arg1, arg2) {
  return window['go']['desktop']['Shell']['InspectSession'](arg1, arg2);
}

export function ListAgents() {
  return window['go']['desktop']['Shell']['ListAgents']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['desktop']['Shell']['ListFiles'](arg1, arg2);
}

export function ListSessionArchives(arg1, arg2) {
  return window['go']['desktop']['Shell']['ListSessionArchives'](arg1, arg2);
}

export function ListSessions(arg1) {
  return window['go']['desktop']['Shell']['ListSessions'](arg1);
}

export function NewSession(arg1) {
  return window['go']['desktop']['Shell']['NewSession'](arg1);
}

export function Notify(arg1, arg2) {
  return window['go']['desktop']['Shell']['Notify'](arg1, arg2);
}

export function OpenExternal(arg1) {
  return window['go']['desktop']['Shell']['OpenExternal'](arg1);
}

export function OutputDir(arg1) {
  return window['go']['desktop']['Shell']['OutputDir'](arg1);
}

export function PickFile(arg1, arg2, arg3) {
  return window['go']['desktop']['Shell']['PickFile'](arg1, arg2, arg3);
}

export function PickFolder(arg1, arg2) {
  return window['go']['desktop']['Shell']['PickFolder'](arg1, arg2);
}

export function RecallSession(arg1, arg2) {
  return window['go']['desktop']['Shell']['RecallSession'](arg1, arg2);
}

export function RestoreSession(arg1, arg2, arg3) {
  return window['go']['desktop']['Shell']['RestoreSession'](arg1, arg2, arg3);
}

export function RevealInFinder(arg1) {
  return window['go']['desktop']['Shell']['RevealInFinder'](arg1);
}

export function RewindSession(arg1, arg2, arg3) {
  return window['go']['desktop']['Shell']['RewindSession'](arg1, arg2, arg3);
}

export function StopAgent(arg1) {
  return window['go']['desktop']['Shell']['StopAgent'](arg1);
}

export function UpdateSecret(arg1, arg2, arg3) {
  return window['go']['desktop']['Shell']['UpdateSecret'](arg1, arg2, arg3);
}

export function UpdateSetting(arg1, arg2, arg3) {
  return window['go']['desktop']['Shell']['UpdateSetting'](arg1, arg2, arg3);
}

export function WatchInputDir(arg1) {
  return window['go']['desktop']['Shell']['WatchInputDir'](arg1);
}

export function WriteFileToInputDir(arg1, arg2, arg3) {
  return window['go']['desktop']['Shell']['WriteFileToInputDir'](arg1, arg2, arg3);
}
