// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function CopyFileToInputDir(arg1:string,arg2:string):Promise<string>;

export function DeleteSession(arg1:string,arg2:string):Promise<void>;

export function DeleteSetting(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function EnsureAgentRunning(arg1:string):Promise<void>;

export function GetIngestState(arg1:string):Promise<desktop.IngestState>;

export function GetSettings():Promise<Record<string, Record<string, any>>>;

export function GetSettingsSchema():Promise<desktop.SettingsSchema>;

export function HasMissingRequired():Promise<Record<string, Array<string>>>;

export function ListAgents():Promise<Array<desktop.AgentInfo>>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<desktop.FileInfo>>;

export function ListSessions(arg1:string):Promise<Array<desktop.SessionMeta>>;

export function NewSession(arg1:string):Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OutputDir(arg1:string):Promise<string>;

export function PickFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PickFolder(arg1:string,arg2:string):Promise<string>;

export function RecallSession(arg1:string,arg2:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function StopAgent(arg1:string):Promise<void>;

export function UpdateSecret(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateSetting(arg1:string,arg2:string,arg3:any):Promise<void>;

export function WatchInputDir(arg1:string):Promise<void>;

export function WriteFileToInputDir(arg1:string,arg2:string,arg3:string):Promise<string>;
