//go:build integration

package integration

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/frankbardon/nexus/pkg/events"
	"github.com/frankbardon/nexus/pkg/testharness"
)

// TestWebSearch_OpenAINative validates the search.provider wiring for
// nexus.search.openai_native end-to-end against a stub OpenAI Responses API.
//
// Flow under test:
//  1. Mocked LLM (via nexus.io.test mock_responses) produces a tool_call to
//     web_search.
//  2. nexus.tool.web emits search.request.
//  3. nexus.search.openai_native POSTs to its base_url (the httptest server).
//  4. The stub returns a Responses-API-shaped JSON payload with url_citation
//     annotations.
//  5. The plugin parses citations into events.SearchResult, fills the
//     synchronous request, and the web tool emits tool.result.
//
// No real API key required: api_key is a stub string and the base_url is
// rerouted to the local httptest server.
func TestWebSearch_OpenAINative(t *testing.T) {
	var hits int32
	var lastBody []byte

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		atomic.AddInt32(&hits, 1)
		// Capture for diagnostic assertions.
		buf := make([]byte, r.ContentLength)
		_, _ = r.Body.Read(buf)
		lastBody = buf

		if got := r.Header.Get("Authorization"); got != "Bearer sk-mock-openai" {
			http.Error(w, "missing/invalid auth: "+got, http.StatusUnauthorized)
			return
		}

		// Responses API shape consumed by openai_native.extractResults.
		// One message block whose content carries two url_citation
		// annotations; both should land as SearchResult entries.
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{
			"id":     "resp_mock_1",
			"object": "response",
			"output": []map[string]any{
				{
					"type": "message",
					"id":   "msg_1",
					"content": []map[string]any{
						{
							"type": "output_text",
							// Index ranges below slice into this string.
							// "OpenAI announced search." → 0..23
							// "Brave released v2."     → 25..43
							"text": "OpenAI announced search. Brave released v2.",
							"annotations": []map[string]any{
								{
									"type":        "url_citation",
									"url":         "https://example.com/openai-search",
									"title":       "OpenAI announces native web_search",
									"start_index": 0,
									"end_index":   23,
								},
								{
									"type":        "url_citation",
									"url":         "https://example.com/brave-v2",
									"title":       "Brave Search v2 release",
									"start_index": 25,
									"end_index":   43,
								},
							},
						},
					},
				},
			},
		})
	}))
	t.Cleanup(srv.Close)

	cfg := writeOpenAINativeConfig(t, srv.URL)

	h := testharness.New(t, cfg, testharness.WithTimeout(30*time.Second))
	h.Run()

	// Plugins under test must be loaded.
	h.AssertBooted(
		"nexus.io.test",
		"nexus.agent.react",
		"nexus.tool.web",
		"nexus.search.openai_native",
	)

	// The mocked LLM should have routed to web_search.
	h.AssertToolCalled("web_search")

	// Stub server should have been hit exactly once.
	if got := atomic.LoadInt32(&hits); got != 1 {
		t.Fatalf("expected 1 hit on stub OpenAI Responses endpoint, got %d (last body=%s)", got, string(lastBody))
	}

	// search.request fires from the web tool, gets filled by openai_native.
	h.AssertEventEmitted("search.request")

	// tool.result must land with the formatted output containing both URLs.
	var sawResult bool
	for _, e := range h.Events() {
		if e.Type != "tool.result" {
			continue
		}
		tr, ok := e.Payload.(events.ToolResult)
		if !ok || tr.Name != "web_search" {
			continue
		}
		sawResult = true
		if tr.Error != "" {
			t.Fatalf("web_search tool.result carries error: %s", tr.Error)
		}
		want := []string{
			"https://example.com/openai-search",
			"https://example.com/brave-v2",
			"OpenAI announces native web_search",
			"Brave Search v2 release",
			"nexus.search.openai_native", // provider tag in formatSearchResults
		}
		for _, w := range want {
			if !strings.Contains(tr.Output, w) {
				t.Errorf("web_search tool.result missing %q in output:\n%s", w, tr.Output)
			}
		}
	}
	if !sawResult {
		t.Fatal("no tool.result event for web_search collected")
	}
}

func writeOpenAINativeConfig(t *testing.T, baseURL string) string {
	t.Helper()
	tmpDir := t.TempDir()
	out := filepath.Join(tmpDir, "test-web-search-openai-native.yaml")

	yaml := fmt.Sprintf(`# Auto-generated by TestWebSearch_OpenAINative.
# Mock-mode: io.test mock_responses replaces the LLM so no provider key is
# required, and nexus.search.openai_native points at an httptest URL.

core:
  log_level: warn
  tick_interval: 5s
  max_concurrent_events: 100
  models:
    default: quick
    quick:
      provider: nexus.llm.anthropic
      model: claude-haiku-4-5-20251001
      max_tokens: 1024
  sessions:
    root: %q
    retention: 30d
    id_format: datetime_short

capabilities:
  search.provider: nexus.search.openai_native

plugins:
  active:
    - nexus.io.test
    - nexus.llm.anthropic
    - nexus.agent.react
    - nexus.memory.capped
    - nexus.tool.web
    - nexus.search.openai_native

  nexus.io.test:
    inputs:
      - "Search the web for OpenAI news."
    input_delay: 100ms
    approval_mode: approve
    timeout: 20s
    mock_responses:
      - tool_calls:
          - name: web_search
            arguments: '{"query":"OpenAI news"}'
      - content: "Here are the top results."

  nexus.llm.anthropic:
    api_key: "sk-mock-not-used-via-mock-responses"

  nexus.agent.react:
    system_prompt: "You are a search agent. Always call web_search first."

  nexus.memory.capped:
    max_messages: 10
    persist: false

  nexus.tool.web:
    search:
      count: 5
      safe_search: moderate

  nexus.search.openai_native:
    api_key: "sk-mock-openai"
    base_url: %q
    model: gpt-4o-mini
    timeout: 5s
`, filepath.Join(tmpDir, "sessions"), baseURL)

	if err := os.WriteFile(out, []byte(yaml), 0o644); err != nil {
		t.Fatalf("write config: %v", err)
	}
	return out
}

