//go:build integration

package integration

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/frankbardon/nexus/pkg/events"
	"github.com/frankbardon/nexus/pkg/testharness"
)

// TestWebSearch_GeminiNative validates the search.provider wiring for
// nexus.search.gemini_native end-to-end against a stub Generative Language
// API endpoint.
//
// Flow under test:
//  1. Mocked LLM (via nexus.io.test mock_responses) produces a tool_call to
//     web_search.
//  2. nexus.tool.web emits search.request.
//  3. nexus.search.gemini_native POSTs to base_url/models/<model>:generateContent
//     with the x-goog-api-key header.
//  4. The stub returns a Gemini-shaped JSON payload with groundingChunks +
//     groundingSupports.
//  5. The plugin parses the grounding metadata into events.SearchResult,
//     fills the synchronous request, and the web tool emits tool.result.
//
// No real API key required: api_key is a stub string and base_url is
// rerouted to the local httptest server.
func TestWebSearch_GeminiNative(t *testing.T) {
	var hits int32
	var lastPath string

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		atomic.AddInt32(&hits, 1)
		lastPath = r.URL.Path

		if got := r.Header.Get("x-goog-api-key"); got != "gemini-mock-key" {
			http.Error(w, "missing/invalid x-goog-api-key: "+got, http.StatusUnauthorized)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{
			"candidates": []map[string]any{
				{
					"content": map[string]any{
						"parts": []map[string]any{
							{"text": "Gemini grounding sample text."},
						},
					},
					"groundingMetadata": map[string]any{
						"groundingChunks": []map[string]any{
							{"web": map[string]any{
								"uri":   "https://example.com/gemini-news",
								"title": "Gemini ships google_search",
							}},
							{"web": map[string]any{
								"uri":   "https://example.com/google-search-tool",
								"title": "Server-side google_search rolls out",
							}},
						},
						"groundingSupports": []map[string]any{
							{
								"segment":               map[string]any{"text": "Gemini ships google_search."},
								"groundingChunkIndices": []int{0},
							},
							{
								"segment":               map[string]any{"text": "Server-side rollout."},
								"groundingChunkIndices": []int{1},
							},
						},
					},
				},
			},
		})
	}))
	t.Cleanup(srv.Close)

	cfg := writeGeminiNativeConfig(t, srv.URL)

	h := testharness.New(t, cfg, testharness.WithTimeout(30*time.Second))
	h.Run()

	h.AssertBooted(
		"nexus.io.test",
		"nexus.agent.react",
		"nexus.tool.web",
		"nexus.search.gemini_native",
	)

	h.AssertToolCalled("web_search")

	if got := atomic.LoadInt32(&hits); got != 1 {
		t.Fatalf("expected 1 hit on stub Gemini endpoint, got %d", got)
	}
	if !strings.Contains(lastPath, "/models/gemini-2.5-flash:generateContent") {
		t.Errorf("unexpected stub path %q, want path containing /models/gemini-2.5-flash:generateContent", lastPath)
	}

	h.AssertEventEmitted("search.request")

	var sawResult bool
	for _, e := range h.Events() {
		if e.Type != "tool.result" {
			continue
		}
		tr, ok := e.Payload.(events.ToolResult)
		if !ok || tr.Name != "web_search" {
			continue
		}
		sawResult = true
		if tr.Error != "" {
			t.Fatalf("web_search tool.result carries error: %s", tr.Error)
		}
		want := []string{
			"https://example.com/gemini-news",
			"https://example.com/google-search-tool",
			"Gemini ships google_search",
			"Server-side google_search rolls out",
			"nexus.search.gemini_native", // provider tag
		}
		for _, w := range want {
			if !strings.Contains(tr.Output, w) {
				t.Errorf("web_search tool.result missing %q in output:\n%s", w, tr.Output)
			}
		}
	}
	if !sawResult {
		t.Fatal("no tool.result event for web_search collected")
	}
}

func writeGeminiNativeConfig(t *testing.T, baseURL string) string {
	t.Helper()
	tmpDir := t.TempDir()
	out := filepath.Join(tmpDir, "test-web-search-gemini-native.yaml")

	yaml := fmt.Sprintf(`# Auto-generated by TestWebSearch_GeminiNative.
# Mock-mode: io.test mock_responses replaces the LLM so no provider key is
# required, and nexus.search.gemini_native points at an httptest URL.

core:
  log_level: warn
  tick_interval: 5s
  max_concurrent_events: 100
  models:
    default: quick
    quick:
      provider: nexus.llm.anthropic
      model: claude-haiku-4-5-20251001
      max_tokens: 1024
  sessions:
    root: %q
    retention: 30d
    id_format: datetime_short

capabilities:
  search.provider: nexus.search.gemini_native

plugins:
  active:
    - nexus.io.test
    - nexus.llm.anthropic
    - nexus.agent.react
    - nexus.memory.capped
    - nexus.tool.web
    - nexus.search.gemini_native

  nexus.io.test:
    inputs:
      - "Search the web for Gemini news."
    input_delay: 100ms
    approval_mode: approve
    timeout: 20s
    mock_responses:
      - tool_calls:
          - name: web_search
            arguments: '{"query":"Gemini news"}'
      - content: "Here are the top results."

  nexus.llm.anthropic:
    api_key: "sk-mock-not-used-via-mock-responses"

  nexus.agent.react:
    system_prompt: "You are a search agent. Always call web_search first."

  nexus.memory.capped:
    max_messages: 10
    persist: false

  nexus.tool.web:
    search:
      count: 5
      safe_search: moderate

  nexus.search.gemini_native:
    api_key: "gemini-mock-key"
    base_url: %q
    model: gemini-2.5-flash
    timeout: 5s
`, filepath.Join(tmpDir, "sessions"), baseURL)

	if err := os.WriteFile(out, []byte(yaml), 0o644); err != nil {
		t.Fatalf("write config: %v", err)
	}
	return out
}
