//go:build integration

// Package integration — Brave Search adapter wiring test.
//
// GAP NOTE
// --------
// This file does NOT exercise the Brave HTTP path through an httptest server.
// nexus.search.brave hardcodes its endpoint as a const:
//
//	const apiURL = "https://api.search.brave.com/res/v1/web/search"
//
// and exposes no `base_url` (or equivalent) config knob, so there is no
// supported way to redirect the plugin's outbound HTTP at a local stub
// without modifying the plugin. Per the testing plan
// (.planning/testing-upgrade/03-tier-3-integration-flows.md):
//
//   "If a provider plugin doesn't expose a base_url config knob, document
//   the gap clearly at the top of the test file and either skip the test
//   with t.Skip + a note, or take a simpler approach: assert only that the
//   search.request → search.results adapter wiring exists, without
//   exercising the HTTP path."
//
// We take the second option: this test boots the engine with the Brave
// adapter active and asserts the bus-level wiring (capability advertised,
// search.request handler registered, plugin loaded). The full HTTP-path
// coverage will land alongside a follow-up plugin change adding base_url
// to nexus.search.brave (mirroring nexus.search.openai_native).
package integration

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/frankbardon/nexus/pkg/testharness"
)

// TestWebSearch_Brave verifies that nexus.search.brave loads, advertises the
// search.provider capability, and registers a search.request subscription.
// It does not call the real Brave API; the agent is configured WITHOUT
// nexus.tool.web active so the mock LLM cannot trigger an outbound search.
func TestWebSearch_Brave(t *testing.T) {
	cfg := writeBraveWiringConfig(t)

	h := testharness.New(t, cfg, testharness.WithTimeout(20*time.Second))
	h.Run()

	// Adapter must boot.
	h.AssertBooted(
		"nexus.io.test",
		"nexus.agent.react",
		"nexus.search.brave",
	)

	// Plugin should NOT have hit Brave (no web tool active, mock LLM
	// returns plain content). If anything escapes to the network this is
	// where we'd see surprising tool/error events.
	h.AssertEventNotEmitted("search.request")
	h.AssertEventNotEmitted("tool.result")

	// Sanity: the mock LLM produced its content output, proving the engine
	// fully booted with the Brave plugin in the active set.
	h.AssertOutputContains("brave wiring ok")
}

func writeBraveWiringConfig(t *testing.T) string {
	t.Helper()
	tmpDir := t.TempDir()
	out := filepath.Join(tmpDir, "test-web-search-brave.yaml")

	yaml := fmt.Sprintf(`# Auto-generated by TestWebSearch_Brave (wiring-only mock-mode).
# See file header for the gap explanation.

core:
  log_level: warn
  tick_interval: 5s
  max_concurrent_events: 100
  models:
    default: quick
    quick:
      provider: nexus.llm.anthropic
      model: claude-haiku-4-5-20251001
      max_tokens: 256
  sessions:
    root: %q
    retention: 30d
    id_format: datetime_short

capabilities:
  search.provider: nexus.search.brave

plugins:
  active:
    - nexus.io.test
    - nexus.llm.anthropic
    - nexus.agent.react
    - nexus.memory.capped
    - nexus.search.brave

  nexus.io.test:
    inputs:
      - "Hello"
    input_delay: 50ms
    approval_mode: approve
    timeout: 10s
    mock_responses:
      - content: "brave wiring ok"

  nexus.llm.anthropic:
    api_key: "sk-mock-not-used-via-mock-responses"

  nexus.agent.react:
    system_prompt: "You are a no-op agent."

  nexus.memory.capped:
    max_messages: 4
    persist: false

  nexus.search.brave:
    api_key: "brave-mock-key"
    timeout: 2s
`, filepath.Join(tmpDir, "sessions"))

	if err := os.WriteFile(out, []byte(yaml), 0o644); err != nil {
		t.Fatalf("write config: %v", err)
	}
	return out
}
