package events

import "time"

// HITLMode controls what shape of response a HITLRequest accepts.
type HITLMode string

const (
	// HITLModeFreeText accepts a single string answer. Choices ignored.
	HITLModeFreeText HITLMode = "free_text"
	// HITLModeChoices restricts the response to one of the provided Choices.
	HITLModeChoices HITLMode = "choices"
	// HITLModeBoth accepts either a chosen ID or freeform text (or both —
	// e.g., "edit" choice with an explanatory note).
	HITLModeBoth HITLMode = "both"
)

// ChoiceKind classifies a HITLChoice for renderers and policy code that
// want to treat allow/reject/edit specially without parsing the label.
// "custom" is the escape hatch for choices that don't fit the canonical
// approval vocabulary (e.g., "Plan A / Plan B / Plan C").
type ChoiceKind string

const (
	ChoiceAllow  ChoiceKind = "allow"
	ChoiceReject ChoiceKind = "reject"
	ChoiceEdit   ChoiceKind = "edit"
	ChoiceCustom ChoiceKind = "custom"
)

// HITLChoice is one option presented to the operator in a multi-choice
// HITLRequest. The ID is canonical and machine-stable; the Label is the
// human-readable text the UI shows. EditedPayload, when non-nil, is the
// override the requesting plugin should apply to its action when this
// choice is picked — used by "edit" choices to carry trimmed args, swapped
// models, and similar.
type HITLChoice struct {
	ID            string         `json:"id"`
	Label         string         `json:"label"`
	Kind          ChoiceKind     `json:"kind,omitempty"`
	EditedPayload map[string]any `json:"edited_payload,omitempty"`
}

// HITLRequest is the unified human-in-the-loop request payload. It
// supersedes AskUser and the design-doc-only ApprovalRequest: any plugin
// that needs an operator's input — clarifying a question, approving a
// destructive tool call, picking among curated plans, or signing off on a
// memory write — emits this single event type.
//
// Exactly one of Prompt, PromptTemplate, or PromptSynthesizer should be
// set. The control/hitl plugin renders the final string at request time;
// IO plugins receive the rendered Prompt and need not understand the
// other two fields.
type HITLRequest struct {
	// ID is stable across the request's lifetime and is what the response
	// correlates against. Generated by the requesting plugin.
	ID string `json:"id"`
	// SessionID is the owning session. Mostly cosmetic — the bus is
	// already session-scoped — but useful for out-of-band CLI tooling.
	SessionID string `json:"session_id,omitempty"`
	// TurnID, when set, ties the request to a specific agent turn so IO
	// plugins can render it inline with the turn it interrupted.
	TurnID string `json:"turn_id,omitempty"`
	// RequesterPlugin is the dotted plugin ID that emitted the request.
	RequesterPlugin string `json:"requester_plugin,omitempty"`
	// ActionKind discriminates what kind of action is awaiting human
	// input: "free_text", "tool.invoke", "memory.longterm.write",
	// "llm.request", or any plugin-defined extension. The control/hitl
	// plugin does not interpret this — it's surfaced verbatim to the IO
	// plugin and to the prompt synthesizer (when configured).
	ActionKind string `json:"action_kind,omitempty"`
	// ActionRef is the opaque payload describing the pending action.
	// Carried alongside the request so the synthesizer can render a
	// context-aware prompt and so the resumed plugin can apply
	// EditedPayload overrides on response.
	ActionRef map[string]any `json:"action_ref,omitempty"`
	// Mode controls whether the response is freeform, multi-choice, or
	// either. Defaults to free_text when zero.
	Mode HITLMode `json:"mode,omitempty"`
	// Choices is the list of options when Mode != free_text.
	Choices []HITLChoice `json:"choices,omitempty"`
	// DefaultChoiceID is the choice picked when the deadline expires
	// without a response. Must reference an existing Choices entry.
	DefaultChoiceID string `json:"default_choice_id,omitempty"`
	// Prompt is the literal rendered question/approval text shown to
	// the operator.
	Prompt string `json:"prompt,omitempty"`
	// PromptTemplate is a Go text/template applied over ActionRef. Set
	// by gates that prefer declarative messaging; control/hitl renders
	// it before forwarding to IO plugins.
	PromptTemplate string `json:"prompt_template,omitempty"`
	// PromptSynthesizer names a registered prompt-synthesizer capability
	// (e.g. "hitl.prompt_synthesizer"). When set, control/hitl invokes
	// the capability and uses the returned text as the rendered Prompt.
	// Falls back to a generic prompt if the capability is unavailable.
	PromptSynthesizer string `json:"prompt_synthesizer,omitempty"`
	// Deadline is an optional absolute timeout. When elapsed, the
	// request auto-resolves with DefaultChoiceID.
	Deadline time.Time `json:"deadline,omitzero"`
	// Metadata is for plugin-specific extensions. Not interpreted by
	// the engine.
	Metadata map[string]any `json:"metadata,omitempty"`
}

// HITLResponse is the operator's answer to a HITLRequest. Exactly one of
// ChoiceID or FreeText is meaningful in HITLModeChoices / HITLModeFreeText;
// in HITLModeBoth either or both may be set.
type HITLResponse struct {
	// RequestID matches HITLRequest.ID.
	RequestID string `json:"request_id"`
	// ChoiceID, when non-empty, is the picked choice's ID.
	ChoiceID string `json:"choice_id,omitempty"`
	// FreeText is the operator's freeform answer when applicable.
	FreeText string `json:"free_text,omitempty"`
	// EditedPayload, when non-nil, supersedes the matching choice's
	// EditedPayload (lets the operator hand-edit on response). The
	// requesting plugin treats this as the action override.
	EditedPayload map[string]any `json:"edited_payload,omitempty"`
	// Cancelled is true when the request was cancelled rather than
	// answered (deadline expired with no DefaultChoiceID, operator
	// invoked `nexus hitl cancel`, etc.).
	Cancelled bool `json:"cancelled,omitempty"`
	// CancelReason carries the cancellation reason when Cancelled.
	CancelReason string `json:"cancel_reason,omitempty"`
}
